FROM python:3.10

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    rustc \
    cargo \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . /app

ENV PYTHONPATH="/app"

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

ENV PORT=8080
EXPOSE 8080

CMD ["sh", "-c", "uvicorn dataset_registry.offchain.server:app --host 0.0.0.0 --port ${PORT}"]

